.

diff --git a/net/seafile-server/files/seafile.init b/net/seafile-server/files/seafile.init
--- a/net/seafile-server/files/seafile.init
+++ b/net/seafile-server/files/seafile.init
@@ -17,7 +17,7 @@ function validate_ccnet_conf_dir () {
 		echo "Error: there is no ccnet config directory."
 		echo "Have you run \"/etc/init.d/seafile setup\"?"
 		echo ""
-		exit -1;
+		exit 1
 	fi
 }
 
@@ -26,7 +26,7 @@ function validate_central_conf_dir () {
 		echo "Error: there is no conf/ directory."
 		echo "Have you run \"/etc/init.d/seafile setup\"?"
 		echo ""
-		exit -1;
+		exit 1
 	fi
 }
 
@@ -41,7 +41,7 @@ function read_seafile_data_dir () {
 		echo "Your seafile server data directory \"${seafile_data_dir}\" is invalid or doesn't exits."
 		echo "Please check it first, or create this directory yourself."
 		echo ""
-		exit 1;
+		exit 1
 	fi
 }
 
@@ -50,7 +50,7 @@ function test_config() {
 		-c "${default_ccnet_conf_dir}" \
 		-d "${seafile_data_dir}" \
 		-F "${central_config_dir}" ; then
-		exit 1;
+		exit 1
 	fi
 }
 
@@ -58,49 +58,46 @@ function check_component_running() {
 	name=$1
 	cmd=$2
 	if pid=$(pgrep -f "$cmd" 2>/dev/null); then
-		echo "[$name] is running, pid $pid. You can stop it by: "
-		echo
-		echo "        kill $pid"
-		echo
-		echo "Stop it and try again."
-		echo
-		exit
+		return 1
 	fi
 }
 
 function validate_already_running () {
-	if pid=$(pgrep -f "seafile-controller -c ${default_ccnet_conf_dir}" 2>/dev/null); then
-		echo "Seafile controller is already running, pid $pid"
-		echo
-		exit 1;
-	fi
-
-	check_component_running "ccnet-server" "ccnet-server -c ${default_ccnet_conf_dir}"
-	check_component_running "seaf-server" "seaf-server -c ${default_ccnet_conf_dir}"
-	check_component_running "fileserver" "fileserver -c ${default_ccnet_conf_dir}"
-	check_component_running "seafdav" "wsgidav.server.run_server"
+	check_component_running "seafile-controller" "seafile-controller -F ${central_config_dir}" || return 1
+	check_component_running "ccnet-server" "ccnet-server -F ${central_config_dir}" || return 1
+	check_component_running "seaf-server" "seaf-server -F ${central_config_dir}" || return 1
+	check_component_running "fileserver" "fileserver -F ${central_config_dir}" || return 1
+	check_component_running "seafdav" "wsgidav.server.run_server" || return 1
 }
 
 function start_seafile_server () {
-	validate_already_running;
-	validate_central_conf_dir;
-	validate_ccnet_conf_dir;
-	read_seafile_data_dir;
-	test_config;
+	if ! validate_already_running; then
+		if [[ "$name" == "seafile-controller" ]]; then
+			echo "Seafile already running."
+		else
+			echo "Error: component [$name] is already running. Please try stopping it manually by running \"kill $pid\"."
+			echo "To force killing the process, use \"kill -9 $pid\"."
+		fi
+		exit 1
+	fi
+	validate_central_conf_dir
+	validate_ccnet_conf_dir
+	read_seafile_data_dir
+	test_config
 
 	echo "Starting seafile server, please wait ..."
 
 	${seaf_controller} \
+		-F "${central_config_dir}" \
 		-c "${default_ccnet_conf_dir}" \
-		-d "${seafile_data_dir}" \
-		-F "${central_config_dir}"
+		-d "${seafile_data_dir}"
 
 	sleep 3
 
 	# check if seafile server started successfully
-	if ! pgrep -f "seafile-controller -c ${default_ccnet_conf_dir}" 2>/dev/null 1>&2; then
+	if ! pgrep -f "seafile-controller -F ${central_config_dir}" 2>/dev/null 1>&2; then
 		echo "Failed to start seafile server"
-		exit 1;
+		exit 1
 	fi
 
 	echo "Seafile server started"
@@ -108,35 +105,41 @@ function start_seafile_server () {
 }
 
 function stop_seafile_server () {
-	if ! pgrep -f "seafile-controller -c ${default_ccnet_conf_dir}" 2>/dev/null 1>&2; then
+	if ! pgrep -f "seafile-controller -F ${central_config_dir}" 2>/dev/null 1>&2; then
 		echo "Seafile server not running"
 	else
 		echo "Stopping seafile server ..."
-		pkill -SIGTERM -f "seafile-controller -c ${default_ccnet_conf_dir}"
-		pkill -f "ccnet-server -c ${default_ccnet_conf_dir}"
-		pkill -f "seaf-server -c ${default_ccnet_conf_dir}"
-		pkill -f "fileserver -c ${default_ccnet_conf_dir}"
+		pkill -SIGTERM -f "seafile-controller -F ${central_config_dir}"
+		pkill -f "ccnet-server -F ${central_config_dir}"
+		pkill -f "seaf-server -F ${central_config_dir}"
+		pkill -f "fileserver -F ${central_config_dir}"
 		pkill -f "soffice.*--invisible --nocrashreport"
 		pkill -f  "wsgidav.server.run_server"
+		retry=1
+		while ! validate_already_running && [ $retry -lt 60 ]; do sleep 1; ((retry++)); done
+		if ! validate_already_running; then
+			echo "Error: [$name] component is still running. Please try stopping it manually by running \"kill $pid\"."
+			echo "To force killing the process, use \"kill -9 $pid\"."
+		fi
+
 	fi
 }
 
 function restart_seafile_server () {
-	stop_seafile_server;
-	sleep 2
-	start_seafile_server;
+	stop_seafile_server
+	start_seafile_server
 }
 
 function start() {
-	start_seafile_server;
+	start_seafile_server
 }
 
 function stop() {
-	stop_seafile_server;
+	stop_seafile_server
 }
 
 function restart() {
-	restart_seafile_server;
+	restart_seafile_server
 }
 
 function setup() {
@@ -146,7 +149,7 @@ function setup() {
 
 function create_admin() {
 	cd "$TOPDIR" && \
-		/usr/bin/seafile-admin setup-admin
+		/usr/bin/seafile-admin create-admin
 }
 
 function reset_admin() {
diff --git a/net/seafile-server/files/seahub.init b/net/seafile-server/files/seahub.init
--- a/net/seafile-server/files/seahub.init
+++ b/net/seafile-server/files/seahub.init
@@ -7,6 +7,7 @@ EXTRA_COMMANDS="clearsessions"
 
 SEAHUB_FASTCGI=0
 SEAHUB_PORT=8000
+SEAHUB_WORKERS=2
 
 [ -f /etc/config/seafile ] && \
 	. /etc/config/seafile
@@ -47,7 +48,7 @@ function validate_ccnet_conf_dir() {
 		echo "Error: there is no ccnet config directory."
 		echo "Have you run '/etc/init.d/seafile setup'?"
 		echo ""
-		exit -1;
+		exit 1
 	fi
 }
 
@@ -62,100 +63,104 @@ function read_seafile_data_dir() {
 		echo "Your seafile server data directory \"${seafile_data_dir}\" is invalid or doesn't exits."
 		echo "Please check it first, or create this directory yourself."
 		echo ""
-		exit 1;
+		exit 1
 	fi
 }
 
 function validate_seahub_running() {
-	if pgrep -f "${manage_py}" 2>/dev/null 1>&2; then
-		echo "Seahub is already running."
-		exit 1;
-	elif pgrep -f "seahub.wsgi:application" 2>/dev/null 1>&2; then
-		echo "Seahub is already running."
-		exit 1;
+	if pid=$(pgrep -f "${manage_py}" 2>/dev/null); then
+		return 1
+	elif pid=$(pgrep -f "seahub.wsgi:application" 2>/dev/null); then
+		return 1
 	fi
 }
 
 function validate_port() {
 	if ! [[ ${SEAHUB_PORT} =~ ^[1-9][0-9]{1,4}$ ]] ; then
-		printf "\033[033m${SEAHUB_PORT}\033[m is not a valid port number\n\n"
+		printf "\033[033m${SEAHUB_PORT}\033[m is not a valid port number\n"
 		exit 1
 	fi
 }
 
 function warning_if_seafile_not_running() {
-	if ! pgrep -f "seafile-controller -c ${default_ccnet_conf_dir}" 2>/dev/null 1>&2; then
+	if ! pgrep -f "seafile-controller -F ${central_config_dir}" 2>/dev/null 1>&2; then
 		echo
-		echo "Warning: seafile-controller not running. Have you run \"/etc/init.d/seafile start\"?"
+		echo "Error: seafile-controller not running. Have you run \"/etc/init.d/seafile start\"?"
 		echo
 		exit 1
 	fi
 }
 
 function prepare_seahub_log_dir() {
-	logdir=${TOPDIR}/logs
-	if ! [[ -d ${logsdir} ]]; then
+	logdir="${TOPDIR}/logs"
+	if ! [[ -d "${logsdir}" ]]; then
 		if ! mkdir -p "${logdir}"; then
-		    echo "ERROR: failed to create logs dir \"${logdir}\""
+		    echo "Error: failed to create log dir \"${logdir}\""
 		    exit 1
 		fi
 	fi
-	export SEAHUB_LOG_DIR=${logdir}
+	export SEAHUB_LOG_DIR="${logdir}"
 }
 
 function before_start() {
-	prepare_env;
-	warning_if_seafile_not_running;
-	validate_seahub_running;
-	prepare_seahub_log_dir;
-	validate_port;
+	prepare_env
+	warning_if_seafile_not_running
+	if ! validate_seahub_running; then
+		echo "Seahub is already running."
+		exit 1
+	fi
+	prepare_seahub_log_dir
+	validate_port
 }
 
 function start_seahub() {
-	before_start;
+	before_start
 	echo "Starting seahub at port ${SEAHUB_PORT} ..."
-	check_init_admin;
+	check_init_admin
 	$PYTHON $gunicorn_exe seahub.wsgi:application -c "${gunicorn_conf}" -b "0.0.0.0:${SEAHUB_PORT}" --preload
 
 	# Ensure seahub is started successfully
-	sleep 5
-	if ! pgrep -f "seahub.wsgi:application" 2>/dev/null 1>&2; then
-		printf "\033[33mError:Seahub failed to start.\033[m\n"
-		echo "Please try to run \"/etc/init.d/seahub start\" again."
-		exit 1;
+	retry=1
+	while ! validate_seahub_running && [[ ! -f "${pidfile}"  ]] && [[ $retry -lt 120 ]]; do sleep 1; ((retry++)); done
+	if ! validate_seahub_running && [[ -f "${pidfile}" ]]; then
+		echo
+		echo "Seahub is started"
+		echo
+	else
+		printf "\033[33mError: Seahub failed to start.\033[m\n"
+		exit 1
 	fi
-	echo
-	echo "Seahub is started"
-	echo
 }
 
 function start_seahub_fastcgi() {
-	before_start;
+	before_start
 
 	# Returns 127.0.0.1 if SEAFILE_FASTCGI_HOST is unset or hasn't got any value,
 	# otherwise returns value of SEAFILE_FASTCGI_HOST environment variable
 	address=`(test -z "$SEAFILE_FASTCGI_HOST" && echo "127.0.0.1") || echo $SEAFILE_FASTCGI_HOST`
 
 	echo "Starting seahub (fastcgi) at ${address}:${SEAHUB_PORT} ..."
-	check_init_admin;
+	check_init_admin
 	$PYTHON "${manage_py}" runfcgi host=${address} port=${SEAHUB_PORT} pidfile=${pidfile} \
-		outlog=${accesslog} errlog=${errorlog}
+		outlog=${accesslog} errlog=${errorlog} workers=${SEAHUB_WORKERS}
 
 	# Ensure seahub is started successfully
-	sleep 5
-	if ! pgrep -f "${manage_py}" 1>/dev/null; then
-		printf "\033[33mError:Seahub failed to start.\033[m\n"
-		exit 1;
+	retry=1
+	while ! validate_seahub_running && [[ ! -f "${pidfile}"  ]] && [[ $retry -lt 120 ]]; do sleep 1; ((retry++)); done
+	if ! validate_seahub_running && [[ -f "${pidfile}" ]]; then
+		echo
+		echo "Seahub is started"
+		echo
+	else
+		printf "\033[33mError: Seahub failed to start.\033[m\n"
+		exit 1
 	fi
-	echo
-	echo "Seahub is started"
-	echo
 }
 
 function prepare_env() {
-	check_python_executable;
-	validate_ccnet_conf_dir;
-	read_seafile_data_dir;
+	check_python_executable
+	validate_ccnet_conf_dir
+	read_seafile_data_dir
 
 	export CCNET_CONF_DIR=${default_ccnet_conf_dir}
 	export SEAFILE_CONF_DIR=${seafile_data_dir}
@@ -164,7 +169,7 @@ function prepare_env() {
 }
 
 function clear_sessions() {
-	prepare_env;
+	prepare_env
 
 	echo "Start clear expired session records ..."
 	$PYTHON "${manage_py}" clearsessions
@@ -180,7 +185,12 @@ function stop_seahub() {
 		echo "Stopping seahub ..."
 		kill ${pid}
 		rm -f ${pidfile}
-		return 0
+		retry=1
+		while ! validate_seahub_running && [ $retry -lt 60 ]; do sleep 1; ((retry++)); done
+		if ! validate_seahub_running; then
+			echo "Error: seahub cannot be stopped. Please try stopping it manually by running \"kill $(echo "$pid" | tr '\n' ' ')\"."
+			echo "To force killing the processes, use \"kill -9 $(echo "$pid" | tr '\n' ' ')\"."
+		fi
 	else
 		echo "Seahub is not running"
 	fi
@@ -207,7 +217,6 @@ function stop() {
 
 function restart() {
 	stop
-	sleep 2
 	start
 }
 
